package `fun`.lifeupapp.calmanager.ui.theme.m3.green

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF3c691b)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFbcf293)
val md_theme_light_onPrimaryContainer = Color(0xFF0b2000)
val md_theme_light_secondary = Color(0xFF56624b)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFdae7ca)
val md_theme_light_onSecondaryContainer = Color(0xFF141e0c)
val md_theme_light_tertiary = Color(0xFF386665)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFbbebea)
val md_theme_light_onTertiaryContainer = Color(0xFF002020)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfdfdf5)
val md_theme_light_onBackground = Color(0xFF1a1c17)
val md_theme_light_surface = Color(0xFFfdfdf5)
val md_theme_light_onSurface = Color(0xFF1a1c17)
val md_theme_light_surfaceVariant = Color(0xFFe0e4d6)
val md_theme_light_onSurfaceVariant = Color(0xFF44483e)
val md_theme_light_outline = Color(0xFF74796d)
val md_theme_light_inverseOnSurface = Color(0xFFf1f1ea)
val md_theme_light_inverseSurface = Color(0xFF2f312c)
val md_theme_light_inversePrimary = Color(0xFFa1d57a)
val md_theme_light_shadow = Color(0xFF000000)

val md_theme_dark_primary = Color(0xFFa1d57a)
val md_theme_dark_onPrimary = Color(0xFF143800)
val md_theme_dark_primaryContainer = Color(0xFF265102)
val md_theme_dark_onPrimaryContainer = Color(0xFFbcf293)
val md_theme_dark_secondary = Color(0xFFbdcbae)
val md_theme_dark_onSecondary = Color(0xFF293420)
val md_theme_dark_secondaryContainer = Color(0xFF3f4a35)
val md_theme_dark_onSecondaryContainer = Color(0xFFdae7ca)
val md_theme_dark_tertiary = Color(0xFFa0cfce)
val md_theme_dark_onTertiary = Color(0xFF003737)
val md_theme_dark_tertiaryContainer = Color(0xFF1e4e4d)
val md_theme_dark_onTertiaryContainer = Color(0xFFbbebea)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1a1c17)
val md_theme_dark_onBackground = Color(0xFFe3e3dc)
val md_theme_dark_surface = Color(0xFF1a1c17)
val md_theme_dark_onSurface = Color(0xFFe3e3dc)
val md_theme_dark_surfaceVariant = Color(0xFF44483e)
val md_theme_dark_onSurfaceVariant = Color(0xFFc4c8bb)
val md_theme_dark_outline = Color(0xFF8e9386)
val md_theme_dark_inverseOnSurface = Color(0xFF1a1c17)
val md_theme_dark_inverseSurface = Color(0xFFe3e3dc)
val md_theme_dark_inversePrimary = Color(0xFF3c691b)
val md_theme_dark_shadow = Color(0xFF000000)

val seed = Color(0xFF1f3211)
val error = Color(0xFFba1b1b)